export const TEAM_DATA = [
  {
    name: "Alex Bandea",
    role_title: "Communications Manager",
    focuses: "",
    practice: "",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero.Sed dignissim lacinia nunc.Curabitur tortor.Pellentesque nibh.Aenean quam.In scelerisque sem at dolor.Maecenas mattis.Sed convallis tristique sem.Proin ut ligula vel nunc egestas porttitor.Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa.Fusce ac turpis quis ligula lacinia aliquet.Mauris ipsum.Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. ",
    leadership: false,
    image: "/uploads/Alex_bw_sq_1.jpg",
  },
  {
    name: "Alexandra Blackwell",
    role_title: "Research Coordinator, Cash and Protection",
    focuses: "economic-wellbeing",
    practice: "Research",
    bio: "Alexandra Blackwell, MPH, currently oversees the IRC’s research portfolio on cash and protection, which seeks to maximize the potential for  cash  and  voucher  assistance to  reduce  violence  outcomes  and  amplify  outcomes  of safety,  empowerment  and  well-being  for crisis-affected  populations. Alexandra has  five  years  of experience working on research on gender-based violence in conflict and humanitarian settings and evaluating programs to prevent and reduce violence, including several studies within the What Works to Prevent Violence global program funded by UK DFID. She has conducted research in Afghanistan, Syria,  Nigeria, Cameroon, and  South  Sudan,  among  other  countries. Alexandra holds a  Master’s degree  from  the George  Washington  University  Milken  Institute  School  of  Public  Health with  a concentration in program design, monitoring and evaluation.",
    leadership: false,
    image: "/uploads/Blackwell-head-shot.jpg",
  },
  {
    name: "Team Member 3",
    role_title: "Role Title",
    focuses: "economic-wellbeing",
    practice: "Research",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ",
    leadership: false,
    image: "https://via.placeholder.com/500?text=Member+3",
  },
  {
    name: "Team Member 4",
    role_title: "Role Title",
    focuses: "economic-wellbeing",
    practice: "Research",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ",
    leadership: false,
    image: "https://via.placeholder.com/500?text=Member+4",
  },
  {
    name: "Team Member 5",
    role_title: "Role Title",
    focuses: "economic-wellbeing",
    practice: "Research",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ",
    leadership: false,
    image: "https://via.placeholder.com/500?text=Member+5",
  },
  {
    name: "Team Member 6",
    role_title: "Role Title",
    focuses: "economic-wellbeing",
    practice: "Research",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ",
    leadership: false,
    image: "https://via.placeholder.com/500?text=Member+6",
  },
  {
    name: "Team Member 7",
    role_title: "Role Title",
    focuses: "economic-wellbeing",
    practice: "Research",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ",
    leadership: false,
    image: "https://via.placeholder.com/500?text=Member+7",
  },
  {
    name: "Team Member 8",
    role_title: "Role Title",
    focuses: "economic-wellbeing",
    practice: "Research",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ",
    leadership: false,
    image: "https://via.placeholder.com/500?text=Member+8",
  }
]